HouseOfFashion/HouseOfFashion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('change.urls')),
    path('change/', include('change.urls')),
    path('users/', include('users.urls')),
    path('images/', include('images.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

from django.contrib.staticfiles.urls import static
from HouseOfFashion import settings
# 用于用户访问 media文件夹下的图片路径重定向
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

HouseOfFashion/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.register, name='register'),
]

HouseOfFashion/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    nickname = models.CharField(max_length=50)

    class Meta(AbstractUser.Meta):
        pass

    def __str__(self):
        return self.username + '-' + self.nickname

HouseOfFashion/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.forms import EmailField


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "nickname")
        field_classes = {
            'username': EmailField,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs.update({'autofocus': True})

        for field_name in self.fields:
            self.fields[field_name].widget.attrs.update({'class': 'form-control'})

        self.fields['username'].widget.attrs.update({'placeholder': '用户名'})
        self.fields['nickname'].widget.attrs.update({'placeholder': '昵称'})
        self.fields['password1'].widget.attrs.update({'placeholder': '密码'})
        self.fields['password2'].widget.attrs.update({'placeholder': '确认密码'})

HouseOfFashion/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from .models import User


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            # form.save()
            username = request.POST['username']
            email = request.POST['username']
            nickname = request.POST['nickname']
            password = request.POST['password1']
            User.objects.create_user(username=username, email=email, nickname=nickname, password=password).save()
            # return to the index
            return redirect("/")
    else:
        form = RegisterForm()

    return render(request, 'users/register.html', context={'form': form})

HouseOfFashion/templates/users/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Register...</title>
    {% load static %}
    <link href="{% static 'change/assets/bookmark.ico' %}" rel="shortcut icon">
    <link href="{% static 'change/assets/bookmark.ico' %}" rel="bookmark">

    <!-- CSS -->
    <link crossorigin="anonymous" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
    <link crossorigin="anonymous" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" rel="stylesheet">
    <!-- JAVASCRIPT -->
    <script crossorigin="anonymous" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js">
    </script>
    <script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js">
    </script>
    <style>
        ul {
            margin-bottom: 0;
        }

        .errorlist {
            padding-inline-start: 0;
        }

        .errorlist li {
            list-style: none;
            color: red;
        }


    </style>
</head>
<body class="py-4" style="background-color: #f5f5f5">
<div class="container">
    <form action="{% url 'users:register' %}" class="col-md-4 offset-md-4" method="POST">
        {% csrf_token %}
        <a class="card-link" href="/">
            <div class="text-center">
                <img class="mb-2" height="72" src="{% static 'change/assets/bookmark.ico' %}" width="72">
                <h1 class="h3 mb-3 font-weight-normal">时尚精品屋</h1>
            </div>
        </a>

        <div class="form-group mb-1">
            <label class="sr-only" for="id_username">用户名：</label>
            {{ form.username }}
            {% if form.username.errors %}
            <small>
                {{ form.username.errors }}
            </small>
            {% endif %}
            <small class="form-text text-muted">必填。请输入您的邮箱作为您的用户名。长度限制为150个字符或更少。</small>
        </div>

        <div class="form-group mb-1">
            <label class="sr-only" for="id_nickname">昵称：</label>
            {{ form.nickname }}
            {% if form.nickkname.errors %}
            <small>
                {{ form.nickname.errors }}
            </small>
            {% endif %}
            <small class="form-text text-muted">必填。长度限制为50个字符或更少</small>
        </div>

        <div class="form-group mb-1">
            <label class="sr-only" for="id_password1">密码：</label>
            {{ form.password1 }}
            {% if form.password1.errors %}
            <small>
                {{ form.password1.errors }}
            </small>
            {% endif %}
            <small class="form-text text-muted">{{ form.password1.help_text|safe }}</small>
        </div>

        <div class="form-group mb-1">
            <label class="sr-only" for="id_password2">确认密码：</label>
            {{ form.password2 }}
            {% if form.password2.errors %}
            <small>
                {{ form.password2.errors }}
            </small>
            {% endif %}
            <small class="form-text text-muted">{{ form.password2.help_text|safe }}</small>
        </div>

        <div class="text-center mt-2">
            <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>
            <a class="my-2 mx-auto" href="#">已有账户？前往登录页</a>
        </div>
    </form>
</div>
</body>
</html>